config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  get 'profile/:username' => 'users#profile', as: :profile

  root to: 'users#index'

  resources :users do
    collection do
      get 'search/:q' => 'users#search', as: :search
    end

    member do
      post 'follow', to: 'relationships#follow_user'
      post 'unfollow', to: 'relationships#unfollow_user'
      post 'accept_follow', to: 'relationships#accept_follow'
      post 'reject_follow', to: 'relationships#reject_follow'
    end
  end

  resources :posts do
    resources :likes, only: %i[new create destroy], shallow: true
    resources :comments, only: %i[new create destroy edit update], shallow: true
  end

  resources :stories, only: %i[new create destroy]

  namespace :api do
    namespace :v1 do
      resources :stories, only: %i[index show]
      resources :relationships, only: %i[index]
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  after_create :increment_comments_count
  after_destroy :decrement_comments_count


  private

  def increment_comments_count
    Post.find(post_id).increment(:comments_count).save
  end

  def decrement_comments_count
    Post.find(post_id).decrement(:comments_count).save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[create]
  before_action :set_comment, only: %i[edit destroy update]

  def create
    authorize Comment
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    authorize @comment
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    authorize @comment
    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:danger] = 'Something worng, try again'
      render root_path
    end
  end

  def destroy
    authorize @comment
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<div class="comment-<%=comment.id.to_s%>">
  <div class="comment-meta">
    <%= cl_image_tag(comment.user.avatar.key, width: 30, height: 30, crop: :fill, class:"img-circle profile-pic") %>
    <%= link_to comment.user.username,profile_path(comment.user.username), class:"text-dark" %>
  </div>
  <% if policy(comment).destroy? %>
    <%= link_to 'Delete', comment_path(comment.id), method: :delete, remote: true, class:"btn btn-sm btn-outline-danger float-end delete-btn-"+comment.id.to_s %>
  <% end %>
  <% if policy(comment).update? %>
    <%= link_to 'Edit', edit_comment_path(comment.id), remote: true, class:"btn btn-sm btn-outline-primary float-end edit-btn-"+comment.id.to_s %>
  <% end %>

  <div class="d-flex justify-content-between comment-content">
    <%= simple_format comment.content %>
    <small class="text-muted">
      <%= time_ago_in_words comment.updated_at%> ago
    </small>
  </div>
</div>

app/views/comments/_edit.html.erb
<div class="comment-<%=@comment.id.to_s%>">
  <div class="comment-meta">
    <%= link_to @comment.user.username,profile_path(@comment.user.username), class:"text-dark" %>
  </div>
  <%= form_for(@comment, remote: true, validate: true) do |f|%>
    <div class="input-group">
      <%= f.text_field :content, class:"form-control" %>
      <div class="input-group-append">
        <%= f.submit "Update", class:"btn btn-outline-success update" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [post, Comment.new], remote: true, validate: true do |f|%>
  <div class="input-group">
    <%= f.text_field :content, class:"form-control" %>
    <div class="input-group-append">
      <%= f.submit "Comment", class:"btn btn-outline-success" %>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$(".comment-list").append("<%= j render @post.comments.last %>");
$("#comment_content").val("");

app/views/comments/destroy.js.erb
$(".comment-<%=@comment.id.to_s%>").remove();

app/views/comments/edit.js.erb
$(".comment-<%=@comment.id.to_s%>").replaceWith("<%= j render('comments/edit') %>");

app/views/comments/update.js.erb
$(".comment-<%=@comment.id.to_s%>").replaceWith("<%= j render 'comments/comment', comment: @comment, remote: true %>");