config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  get 'profile/:username' => 'users#profile', as: :profile

  root to: 'users#index'

  resources :users do
    collection do
      get 'search/:q' => 'users#search', as: :search
    end

    member do
      post 'follow', to: 'relationships#follow_user'
      post 'unfollow', to: 'relationships#unfollow_user'
      post 'accept_follow', to: 'relationships#accept_follow'
      post 'reject_follow', to: 'relationships#reject_follow'
    end
  end

  resources :posts do
    resources :likes, only: %i[new create destroy], shallow: true
    resources :comments, only: %i[new create destroy edit update], shallow: true
  end

  resources :stories, only: %i[new create destroy]

  namespace :api do
    namespace :v1 do
      resources :stories, only: %i[index show]
      resources :relationships, only: %i[index]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_]+\z/ }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 20 }, format: { with: /\A[a-zA-Z]+\z/ }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 20 }, format: { with: /\A[a-zA-Z]+\z/ }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password_confirmation, presence: true

  has_many :posts, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 'follows' relationship objects where the user is being followed.
  has_many :follower_relationships, foreign_key: :following_id, class_name: :Follow, dependent: :destroy,
                                    inverse_of: :following
  # The next line goes the next step and accesses a user's followers through those relationships which are 'accepted'.
  has_many :followers, -> { Follow.accepted }, through: :follower_relationships

  #  same for the 'following' relationships
  has_many :following_relationships, foreign_key: :follower_id, class_name: :Follow, dependent: :destroy,
                                     inverse_of: :follower
  has_many :following, -> { Follow.accepted }, through: :following_relationships

  has_one_attached :avatar, dependent: :destroy
  after_commit :add_default_avatar, on: %i[create update]

  def liked?(post)
    likes.where(post_id: post.id).exists?
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def follow(user_id)
    following_relationships.create(following_id: user_id)
    following = User.find(user_id)
    return true if following.private?

    following_relationships.find_by(following_id: user_id).update(status: 'accepted')
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def following?(user_id)
    following.include?(User.find(user_id))
  end

  def pending?(user_id)
    @relationship = following_relationships.find_by(following_id: user_id)
    @relationship.status == 'pending' unless @relationship.nil?
  end

  def follower_count
    followers.count
  end

  def following_count
    following_relationships.count
  end

  def self.text_search(query)
    if query.present?
      where('username ILIKE ?', "%#{query}%")
    else
      all
    end
  end

  private

  def add_default_avatar
    return if avatar.attached?

    avatar.attach(
      io: File.open(Rails.root.join('app/assets/images/default_profile.jpg')),
      filename: 'default_profile.jpg',
      content_type: 'image/jpg'
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[profile destroy]
  def index
    load_index
    load_suggestions
  end

  def profile
    @posts = @user.posts
  end

  def search
    @find = User.text_search(params[:q])
    render json: @find
  end

  def destroy
    ActiveRecord::Base.transaction do
      @user.destroy
      @user.comments.destroy_all
      @user.likes.destroy_all
      @user.posts.each(&:purge)
      redirect_to root_path, flash: { success: 'User deleted!' }
    end
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end

  def load_index
    @posts = Post.of_followed_users(current_user.following + [current_user])
    @stories = Story.of_followed_users(current_user.following + [current_user])
  end

  def load_suggestions
    following_ids = current_user.following_relationships.pluck(:following_id)
    @follower_suggestions = User.where.not(id: following_ids).limit(4) - [current_user]
    @pending_follows = current_user.follower_relationships.where(status: 'pending')
  end
end

app/helpers/users_helper.rb
module UsersHelper
  delegate :following?, to: :current_user
  delegate :pending?, to: :current_user
end

app/views/users/_follower_suggestions.html.erb
<% @pending_follows.each do |follow| %>
  <div class="recommended-followers">
    <div class="row">
      <div class="col-2">
        <%= cl_image_tag(follow.follower.avatar.key, width: 50, height: 50, crop: :fill, class:"img-circle profile-pic") %>
      </div>
      <div class="col-10">
        <%= link_to follow.follower.username, profile_path(follow.follower.username), class:"text-dark" %>
        <div class="float-end">
          <%= link_to "Accept", accept_follow_user_path(follow.follower.id), remote: true, class: "btn follow-btn", id: 'accept-btn-'+follow.follower.username, method: :post%>
          <%= link_to "Cancel", reject_follow_user_path(follow.follower.id), remote: true, class: "btn unfollow-btn", id: 'reject-btn-'+follow.follower.username, method: :post%>
        </div>
        <p class="text-muted">Pending</p>
      </div>
  </div>
<%end%>

<% @follower_suggestions.each do |user| %>
  <div class="recommended-followers">
    <div class="row">
      <div class="col-2">
        <%= cl_image_tag(user.avatar.key, width: 50, height: 50, crop: :fill, class:"img-circle profile-pic") %>
      </div>
      <div class="col-10">
        <%= link_to user.username, profile_path(user.username), class:"text-dark" %>
        <div class="float-end">
          <%= link_to "Follow", follow_user_path(user.id), remote: true, class: "btn follow-btn", id: 'follow-btn-'+user.username, method: :post%>
        </div>
        <p class="text-muted"><%= user.created_at > 2.days.ago ? "New here" : "Followed by " %></p>
      </div>
  </div>
<%end%>
<% if @follower_suggestions.empty? %>
  <p class="text-muted">No suggestions</p>
<% end %>

app/views/users/accept_follow.js.erb
$("#reject-btn-<%=@user.username%>")
.hide()

$("#accept-btn-<%=@user.username%>")
.attr("class", "btn unfollow-btn")
.text("Accpeted")
.attr("href", "<%= reject_follow_user_path %>")
.attr("id", "reject-btn-<%=@user.username%>");

app/views/users/follow_user.js.erb
$("#follower-count").text("<%= @follower_count %> followers");
$("#follow-btn-<%=@user.username%>")
.attr("class", "btn unfollow-btn")
.text("Following")
.attr("href", "<%= unfollow_user_path %>")
.attr("id", "unfollow-btn-<%=@user.username%>");

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= render "layouts/flash" %>
      <h2>Stories...</h2>
      <br>
      <%= render @stories%>
      <hr class="border-2 border-top">
      <h2>Posts...</h2>
      <br>
      <%= render @posts %>
    </div>

    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <%= cl_image_tag(current_user.avatar.key, width: 100, height: 100, crop: :fill, class:"img-circle profile-pic float-end") %>
          <h5 class="card-title">
            <%= current_user.username %>
          </h5>
          <p class="card-text">
            <%= current_user.full_name %>
          </p>
        </div>
      </div>
      <br>

      <div class= "follower-suggestions">
        <%= link_to "View All", "#", class:"float-end text-dark"%>
        <p class="text-muted">suggestions for you</p>
        <%= render "users/follower_suggestions"%>
      </div>
    </div>
  </div>
</div>

app/views/users/pending_follow.js.erb
$("#follow-btn-<%=@user.username%>")
.attr("class", "btn unfollow-btn")
.text("Pending")
.attr("href", "<%= unfollow_user_path %>")
.attr("id", "unfollow-btn-<%=@user.username%>");

app/views/users/profile.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-4'>
      <%= cl_image_tag(@user.avatar.key, width: 150, height: 150, crop: :fill, class:"img-circle profile-pic") %>
    </div>
    <div class='col-8'>
      <h1> <%=@user.full_name%> </h1>
      <span>
        <% if policy(@user).update? %>
          <%= link_to edit_user_registration_path(current_user.username), class: "btn btn-outline-secondary" do %>
            <i class="fas fa-edit"></i> Edit Profile
          <% end %>
        <% elsif following? @user.id %>
          <%= link_to "Following", unfollow_user_path(@user), remote: true, class: "btn unfollow-btn", id: 'unfollow-btn-'+@user.username, method: :post%>
        <% elsif pending? @user.id %>
          <%= link_to "Pending", unfollow_user_path(@user), remote: true, class: "btn unfollow-btn", id: 'unfollow-btn-'+@user.username, method: :post%>
        <% else %>
          <%= link_to "Follow", follow_user_path(@user), remote: true, class: "btn follow-btn", id: 'follow-btn-'+@user.username, method: :post%>
        <% end %>
      </span>
      <div class="row profile-stats">
        <div class="col-4">
          <%=@user.posts.count%> posts
        </div>
        <div class="col-4" id= "follower-count">
          <%=@user.follower_count%> followers
        </div>
        <div class="col-4">
          <%=@user.following_count%> following
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class='row profile-posts'>

    <% if following? @user.id%>
        <%= render "posts/profile" %>
    <% elsif !@user.private || policy(@user).update?  %>
        <%= render "posts/profile" %>
    <% end %>

  </div>
</div>

app/views/users/reject_follow.js.erb
$("#reject-btn-<%=@user.username%>")
.attr("class", "btn unfollow-btn")
.text("Rejected")
.attr("href", "<%= root_path %>")

$("#accept-btn-<%=@user.username%>")
.hide()

app/views/users/unfollow_user.js.erb
$("#follower-count").text("<%= @follower_count %> followers");
$("#unfollow-btn-<%=@user.username%>")
.text("Follow")
.attr("class", "btn follow-btn")
.attr("href", "<%= follow_user_path %>")
.attr("id", "follow-btn-<%=@user.username%>");