config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  get 'profile/:username' => 'users#profile', as: :profile

  root to: 'users#index'

  resources :users do
    collection do
      get 'search/:q' => 'users#search', as: :search
    end

    member do
      post 'follow', to: 'relationships#follow_user'
      post 'unfollow', to: 'relationships#unfollow_user'
      post 'accept_follow', to: 'relationships#accept_follow'
      post 'reject_follow', to: 'relationships#reject_follow'
    end
  end

  resources :posts do
    resources :likes, only: %i[new create destroy], shallow: true
    resources :comments, only: %i[new create destroy edit update], shallow: true
  end

  resources :stories, only: %i[new create destroy]

  namespace :api do
    namespace :v1 do
      resources :stories, only: %i[index show]
      resources :relationships, only: %i[index]
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images, dependent: :destroy
  # defining scope using lamba function that returns followed users posts
  scope :of_followed_users, ->(following_users) { where user_id: following_users }

  default_scope { order created_at: :desc }
  validates :user_id, presence: true
  validates :images, presence: true
  validate :images_format


  private

  def images_format
    errors.add(:images, 'missing') unless images.attached?

    images.each do |image|
      errors.add(:images, 'must be a JPEG or PNG') unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    redirect_to root_path
  end

  def create
    authorize Post
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      redirect_to root_path, flash: { success: 'Post created!' }
    else
      render :new, flash: { danger: 'Post not created!' }
    end
  end

  def new
    @post = Post.new
  end

  def show; end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to root_path, flash: { success: 'Post updated!' }
    else
      redirect_to edit_post_path, flash: { danger: 'Post not updated!' }
    end
  end

  def destroy
    authorize @post
    ActiveRecord::Base.transaction do
      @post.destroy
      @post.comments.destroy_all
      @post.likes.destroy_all
      @post.images.each(&:purge)
      redirect_to root_path, flash: { success: 'Post deleted!' }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption, images: [])
  end
end

app/views/posts/_form.html.erb
<%=form_for @post, html: {multipart: true}, validate: true do |f|%>
  <div class="form-group">
    <%=f.label "images (max 10)" %>
    <%= f.file_field :images, multiple: true, direct_upload: true, class:"form-control", accept: "image/png, image/jpg, image/jpeg" %>
  </div>
  <br>
  <div class="form-group">
    <%=f.label :caption%>
    <%= f.text_area :caption, class:"form-control" %>
  </div>

  <%= f.submit 'Save Post', class: 'btn btn-outline-success' %>
<%end%>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-meta">
    <%= cl_image_tag(post.user.avatar.key, width: 50, height: 50, crop: :fill, class:"img-circle profile-pic") if post.images_attachments %>
    <%= link_to post.user.username, profile_path(post.user.username), class:"text-dark" %>
  </div>
  <% post.images.each do |image| %>
    <%= cl_image_tag(image.key, class:"img  img-fluid", style:"inline-size: -moz-available;")%>
  <%end%>

  <div class="post-details">
    <div class="post-actions">
      <%= link_to post_likes_path(post), method: :post, remote: true do %>
        <i class="fa fa-2x fa-heart post-like like-<%= post.id %> <%= 'active' if current_user.liked? post %>"></i>
      <% end %>

      <%= link_to post_path(post.id) do %>
        <i class="fa fa-2x fa-comment post-comment"></i>
      <% end %>
    </div>

    <p><strong id="post-<%= post.id %>-likes">
      <%= post.likes_count %> likes
    </strong></p>
    <p><strong>
      <%= link_to post.user.username, profile_path(post.user.username), class:"text-dark"%>
    </strong></p>
    <%= simple_format post.caption%>
    <small class="text-muted">
      <%= time_ago_in_words post.created_at%> ago
    </small>
  </div>

  <div class="comment-box">
    <div class="comment-form">
      <%= render "comments/form", post: post%>
    </div>

    <div class="comment-list">
      <% if post.comments.exists? %>
        <%= render post.comments %>
      <% end %>
    </div>
  </div>
  <% if policy(post).update? %>
    <%= link_to 'edit', edit_post_path(post), class: 'btn btn-outline-secondary' %>
    <%= link_to 'delete', post, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %>
  <% end %>

</div>

app/views/posts/_profile.html.erb
<%@posts.each do |post|%>
  <div class='col-4'>
    <div class='post post-square' style="background: url(<%= cl_image_path(post.images[0].key) %>) no-repeat center top">
      <%= link_to post_path(post) do %>
        <div class="post-stats">
          <div class="inner-post-stats">
            <i class="fa fa-heart"></i> <%= post.likes_count%>
            <i class="fa fa-comment m-l-15"></i> <%= post.comments_count%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<%end%>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form'%>

app/views/posts/like.js.erb
<% if @success == true %>
  $(".like-<%= @post_id %>").addClass("active");
<% else %>
  $(".like-<%= @post_id %>").removeClass("active");
<% end %>

$("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render "layouts/flash" %>
<%= render 'form'%>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="post">
        <% @post.images.each do |image| %>
          <%= cl_image_tag(image.key, class:"img  img-fluid", style:"inline-size: -moz-available;")%>
        <%end%>
      </div>
    </div>

    <div class="col-4">
      <div class="post-meta">
        <%= cl_image_tag(@post.user.avatar.key, width: 50, height: 50, crop: :fill, class:"img-circle profile-pic") %>
        <%= link_to @post.user.username, profile_path(@post.user.username), class:"text-dark" %>
      </div>
      <div class="comment-box">
        <div class="comment-list">
          <%= simple_format @post.caption%>
          <% if @post.comments.exists? %>
            <%= render @post.comments %>
          <% end %>
        </div>
        <div class="comment-form">
          <%= render "comments/form", post: @post %>
        </div>
      </div>
      <div class="post-details">
        <div class="post-actions">
          <%= link_to post_likes_path(@post), method: :post, remote: true do %>
            <i class="fa fa-2x fa-heart post-like like-<%= @post.id %> <%= 'active' if current_user.liked? @post %>"></i>
          <% end %>

          <%= link_to post_path(@post.id) do %>
            <i class="fa fa-2x fa-comment post-comment"></i>
          <% end %>
        </div>

        <p><strong id="post-<%= @post.id %>-likes">
          <%= @post.likes_count %> likes
        </strong></p>
        <small class="text-muted">
          <%= time_ago_in_words @post.created_at%> ago
        </small>
      </div>
    </div>
  </div>
</div>