config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  get 'profile/:username' => 'users#profile', as: :profile

  root to: 'users#index'

  resources :users do
    collection do
      get 'search/:q' => 'users#search', as: :search
    end

    member do
      post 'follow', to: 'relationships#follow_user'
      post 'unfollow', to: 'relationships#unfollow_user'
      post 'accept_follow', to: 'relationships#accept_follow'
      post 'reject_follow', to: 'relationships#reject_follow'
    end
  end

  resources :posts do
    resources :likes, only: %i[new create destroy], shallow: true
    resources :comments, only: %i[new create destroy edit update], shallow: true
  end

  resources :stories, only: %i[new create destroy]

  namespace :api do
    namespace :v1 do
      resources :stories, only: %i[index show]
      resources :relationships, only: %i[index]
    end
  end

end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <% if type == "alert"%>
      <% type= 'danger'%>
    <% end %>
    <% if type == "notice"%>
      <% type= 'primary'%>
    <% end %>
    <div class="alert alert-<%= type %>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_public_nav.html.erb
<li class="nav-item">
  <a class="nav-link" href="/users/sign_in">
    <i class="fas fa-sign-in"></i> Sign In
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="/users/sign_up">
    <i class="fas fa-user-plus"></i> Sign Up
  </a>
</li>

app/views/layouts/_user_nav.html.erb
<div role="search">
  <%= form_tag root_path, class: 'navbar-form', method: :get do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], id: 'typeahead', class: 'search-input form-control', placeholder: 'Search users' %>
    </div>
  <% end %>
</div>

<li class="nav-item">
  <%= link_to root_path, class: "nav-link active" do %>
    <i class="fas fa-home"></i> Home
  <% end %>
</li>

<li class="nav-item">
  <%= link_to new_post_path, class: "nav-link active" do %>
    <i class="fas fa-plus"></i> New Post
  <% end %>
</li>
<li class="nav-item">
  <%= link_to new_story_path, class: "nav-link active" do %>
    <i class="fas fa-plus"></i> New Story
  <% end %>
</li>
<li class="nav-item">
  <%= link_to profile_path(current_user.username), class: "nav-link active" do %>
    <%= current_user.full_name %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link active" do %>
    <i class="fas fa-sign-out-alt"></i>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Railsgram</title>

        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">
                <i class="fa fa-camera"></i> | Railsgram
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <% if policy(User).index? %>
                        <%= render "layouts/user_nav"%>
                    <%else%>
                        <%= render "layouts/public_nav"%>
                    <%end%>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container">
        <div>
           <%= yield %>
        </div>
    </div>

  </body>
</html>